import type { Metadata } from "next";
import { Roboto, Nunito } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar/NavBar";
import Footer from "@/components/Footer/Footer";
import { AuthProvider } from "@/contexts/authContext";
import { ToastContainer } from "react-toastify";

const primaryFont = Nunito({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-secondary"
});

const secondaryFont = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-primary"
});

export const metadata: Metadata = {
  title: "SamShopping",
  description: "Generated by create next app for SoyHenry", 
   icons: {
    icon: '/logo.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
    <html lang="en" className={`${primaryFont.variable} ${secondaryFont.variable}`}>
      <body className={primaryFont.className}>
      <ToastContainer />
      <NavBar/>
        <main> {children}</main>
      <Footer/>
      </body>
    </html>
    </AuthProvider>
  );
}
